### ISSUE TITLE
pritunl vs archive

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [pritunl/archlinux#2]
Sébastien and Zachary:

both of your sites:
http://archive.archlinux.org/ (Sébastien)
http://mirror.pritunl.com/archlinux/ (Zachary)

serve the same purpose, but are not interchangeable;
can you guys please agree on the same site layout, 
so they can be used as fall back to each other?

thank you.

**Comment by Andrei-Pozolotin** [comment]
see https://github.com/seblu/archivetools/issues/4

**Comment by zachhuff386** [comment]
The repositories sync at different times and don't contain the same package versions.
